import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

import { Providers } from './../utils/chakra/provider.chakra';
import { VeergeAssistant } from '@/components/VeergeAssistant/AssistantModal';

export const metadata: Metadata = {
  title: 'Veerge App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
      <VeergeAssistant className="" />
        <Providers>{children}</Providers>
       
        </body>
    </html>
  )
}
